### ISSUE TITLE
Internationalize this plugin

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-network-catalog#127]
Now that this plugin is public, we should make sure that it is properly internationalized and can be translated into whatever languages users would like to use. See https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/ for details. We currently use Transifex to internationalize our other open source projects: (see https://github.com/pressbooks/private/wiki/Translation + https://www.transifex.com/pressbooks/pressbooks/dashboard/) but are interested in using CrowdIn for future projects. I requested an open source license in July 2021 and have renewed our application for an free open source enterprise account.

**Comment by greatislander** [comment]
@SteelWagstaff good opportunity to set up CrowdIn.

**Comment by SteelWagstaff** [comment]
Yes -- agree. Just reapplied for open source license for CrowdIn.

**Comment by richard015ar** [comment]
Does the DoD include the research and possible implementation of CrowdIn? If yes, I think it should include documentation about how we could implement it in other repos.

**Comment by SteelWagstaff** [comment]
Yes -- if I can get an open source license of CrowdIn, I would produce documentation for moving out other projects there. See https://support.crowdin.com/enterprise/project-settings/

**Comment by cmurtagh** [comment]
What impact (if any) does using non-free SaaS tool CrowdIn have on open source users?

**Comment by SteelWagstaff** [comment]
None. It would be a replacement for the non-free SaaS tool Transifex.

**Comment by SteelWagstaff** [comment]
Here's what I did this afternoon:
1. Created a new Transifex project for this repo
2. Created a pot file using this command: `wp i18n make-pot . languages/pressbooks-network-catalog.pot --domain=pressbooks-network-catalog --slug=pressbooks-network-catalog --package-name="Pressbooks Network Catalog" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-network-catalog/issues\"}"`
3. Uploaded the .pot file to the Transifex project and produced French language translations for all strings in the Transifex client
4. Merged a PR adding update-pot and update-translation actions which match what we're doing in other repos
5. Added a `TX_TOKEN` secret to this repo
6. Ran these actions to generate new .pot files and pull in any .po and .mo translation files from Transifex

**Comment by greatislander** [comment]
Ah, nevermind.

**Comment by SteelWagstaff** [comment]
I was having problems with the update-translations.yml file and so I decided to the following:
1. integrated this repo with the transifex GitHub integration
2. created a transifex.yml file following these instructions: https://help.transifex.com/en/articles/6265125-github-via-transifex-ui#section-more-examples-of-yaml-configurations
3. Set up the configuration so that it will automatically commit .po files to the repo whenever translations reach 100% or are updated
![Screenshot from 2022-11-09 20-02-43](https://user-images.githubusercontent.com/13485451/200997879-2078175c-fc31-475d-a2ba-4cfa08835916.png)
4. Manually synced translation files from GitHub to transifex
5. Generated the .po files with `wp i18n make-mo languages` and commited them to development branch

To do: figure out some method for automating that combines older and new approach. Issues to resolve:
1. We don't have any automated method for pushing .pot files to GitHub in any of our existing repos right now. Update .pot only updates the file in the repo, but never sends it to Transifex(!): https://github.com/pressbooks/pressbooks/blob/dev/.github/workflows/update-pot.yml. We could fix this by adding a `tx push` command.
2. The update translation automation uses the old Python-based transifex client: https://github.com/pressbooks/pressbooks/blob/e06878135c0a83e6e89fb3ca35b92926b3bbbffb/.github/workflows/update-translations.yml#L12-L13. They've since switched to a Go based one which is installed differently and which uses their new API: https://developers.transifex.com/docs/cli#differences-with-the-previous-version. 
3. The integration with Transifex I just created doesn't automatically create or commit .mo files (this is only done in the update translations CI action Ned created for us): https://github.com/pressbooks/pressbooks/blob/e06878135c0a83e6e89fb3ca35b92926b3bbbffb/.github/workflows/update-translations.yml#L23-L29

**Comment by SteelWagstaff** [comment]
Tonight I just received confirmation that our open source organization was renewed in CrowdIn. Tomorrow I will continue my research by seeing what I can do via their automation/integration with this project and their documentation: https://support.crowdin.com/github-integration/

**Comment by andrii-bodnar** [comment]
Hi @SteelWagstaff,

Besides the native GitHub Connector, there is also a possibility to use GitHub Action:
https://github.com/crowdin/github-action

Please let me know if you have any questions regarding the Crowdin integration

**Comment by comradekingu** [comment]
You don't want Crowdin, in the same vein that TX is a horrendous terms of service dystopia.
It messes up the locales, and it isn't a good tool.
@SteelWagstaff Crowdin is just as non-free as TX.

https://hosted.weblate.org/hosting/ is the far superior alternative, which can also be self-hosted.

**Comment by SteelWagstaff** [comment]
We sticking with Transifex for now. May reassess this in the future for this and other plugins.
