### ISSUE TITLE
Remove institutions & publishers with no results

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-network-catalog#131]
Several of our networks are showing values in the subject, institution & publisher filters which have no results. I think they're returning any value present in all books on the network, not just values for books in the catalog.

See:
https://pressbooks.lib.jmu.edu/catalog/
(University of Minnesota & Wagstaff) 
![Screenshot from 2022-11-10 10-47-17](https://user-images.githubusercontent.com/13485451/201180857-e2e7a35e-a4e0-4c23-9f7c-92ae65def356.png)
or https://university.pressbooks.pub/catalog/ (several of the Institution & publisher filters aren't used by any books in the catalog)
![Screenshot from 2022-11-10 10-49-24](https://user-images.githubusercontent.com/13485451/201181024-b93099f8-21dc-40ac-976d-e517b7d1a50e.png)

Desired behaviour: the filter only includes values for books which are in the catalog

Current behaviour: the filter returns values for all books in the network, whether they're in the catalog or not.

**Comment by fdalcin** [comment]
[This](https://github.com/pressbooks/pressbooks-network-catalog/blob/fbb6977cf56063a50507bcd282653ca88627c0a1/src/Filters/Institution.php#L18) is an example of how we get the possible filters to be shown. 

One option would be to update the Data Collector method to accept a new parameter to filter possible values only for books that are in the catalog (this would require changing core plugin + catalog plugin).  Another option would be to duplicate the method with that change only for this plugin.

**Comment by richard015ar** [comment]
current data collector method: https://github.com/pressbooks/pressbooks/blob/dev/inc/datacollector/class-book.php#L518

**Comment by fdalcin** [comment]
**Testing**

Once this is deployed to integrations follow steps described on pressbooks/pressbooks-network-catalog#136

**Comment by SteelWagstaff** [comment]
Works as expected on integrations.

**Comment by beckej13820** [comment]
I'm still seeing this behavior using latest version of the plugin.
