### ISSUE TITLE
Render html tags in 'short description' as HTML in book cards

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-network-catalog#138]
Some users have entered HTML elements like `<br/>`, `<a>`, `<strong>`, `<em>` and more in the 'short description' field in book info (which does not include a rich text editor). When present in the long description, these are rendered as expected in book cards.
![Screenshot from 2022-11-29 11-08-58](https://user-images.githubusercontent.com/13485451/204623825-edbc999b-a234-43aa-b658-3550ae00c355.png)

When manually entered in the short description, these are not rendered in book cards.
![Screenshot from 2022-11-29 10-49-25.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/b7353417-e56d-4dd3-856e-9c41ef22e492)

When present, these should be rendered as line breaks and links, bold or italic text in the book card. See https://open.oregonstate.education/ for several examples of escaped HTML. Perhaps we want to change the permitted input field for short descriptions in book info?

Blade template that renders the unescaped content: https://github.com/pressbooks/pressbooks-network-catalog/blob/8c45a44f314a9056965de329e26b144d39c16bd7/resources/views/partials/book-card.blade.php#L57-L63

**Comment by fdalcin** [comment]
[pressbooks/pressbooks-book](https://github.com/pressbooks/pressbooks-book) uses a helper method called `pb_decode` to fix that and render HTML elements properly, [see here](https://github.com/pressbooks/pressbooks-book/blob/4544a24a597dc04b29c45867647fadac5db45d94/partials/content-cover-book-header.php#L93).

If we wrap the short description it should fix the issue in the catalog the same way

```php
{!! pb_decode($book->shortDescription) !!} 
```

**Comment by SteelWagstaff** [comment]
Works as expected and ready for release.
