### ISSUE TITLE
Abrupt line breaks in book descriptions

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-network-catalog#174]
In book descriptions in the new network catalog, line breaks are consistently occurring within words. Instead of hyphenating the word or pushing it onto a new line, words are cut and continued on the next line. See 'textboo,' 'ada,' or 'an' ('and') in this example:

<img width="1042" alt="Screenshot 2023-03-08 at 7 22 15 AM" src="https://user-images.githubusercontent.com/44182629/223753866-6b7abe2a-35e7-4e49-be4a-362f8814db13.png">

This occurs on Chrome, Firefox, and Safari, and affects both long and short book descriptions.

This was a related but not identical issue: https://github.com/pressbooks/pressbooks-network-catalog/issues/46.

**Expected behaviour:** If a word can't fit on the same line, it will be hyphenated and continued on the next line or pushed to the next line. Either would be easier to read than the current behaviour.

**Actual behaviour:** If a word can't fit on the same line, a line break occurs within the word without any hyphenation.

**Comment by SteelWagstaff** [comment]
Solution is to change the word-break property to break-word instead of break-all in https://github.com/pressbooks/pressbooks-network-catalog/blob/8819621f7d3582818a1855e8123de7e09b2f999f/assets/css/book-card.css#L52.

**Comment by SteelWagstaff** [comment]
Fixed and ready for release
