### ISSUE TITLE
Authors not displaying for CAUL

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-network-catalog#195]
The OER Collective in Australia has reported that authors do not appear on book cards in their catalog: https://oercollective.caul.edu.au/catalogue/
![screencapture-oercollective-caul-edu-au-catalogue-2023-04-19-08_47_53](https://user-images.githubusercontent.com/13485451/233130363-67e7dc30-2a68-45ae-a719-6dfae3f47807.png)

Each of these books does in fact have authors. See 
![Screenshot from 2023-04-19 08-49-26](https://user-images.githubusercontent.com/13485451/233130660-d0b55a30-b8fa-4fdc-abaa-e0424b3b0c60.png)
and
![Screenshot from 2023-04-19 08-50-02](https://user-images.githubusercontent.com/13485451/233130816-626014e7-c41d-4aee-acb6-fdb357dbd7a5.png)

The author information is available via API:
![Screenshot from 2023-04-19 08-41-53](https://user-images.githubusercontent.com/13485451/233130132-01a66676-9398-45cf-8edf-bc87848a0311.png)

However, some (but not all!) of these books also lack author information in Algolia and the Directory:
![Screenshot from 2023-04-19 08-43-28](https://user-images.githubusercontent.com/13485451/233130115-bb4d02dd-626a-4d80-9b22-1a01afb03d63.png)
See: 
![screencapture-pressbooks-directory-2023-04-19-08_51_38](https://user-images.githubusercontent.com/13485451/233131417-6786a662-f57c-4fdb-81b4-19f61b9193e8.png)

**Comment by arzola** [comment]
One thing that I noticed is the books that are not appearing on the directory contains the following key in the API
<img width="620" alt="Pasted_Image_2023-04-19__12_31_PM" src="https://user-images.githubusercontent.com/4997549/233140863-693fd4a8-08bf-4e7e-a44e-818284c3e592.png">

**Comment by arzola** [comment]
This fix the network catalog issue https://github.com/pressbooks/pressbooks/pull/3289

**Comment by SteelWagstaff** [comment]
Tested and working as expected on staging network. Ready for release!
