### ISSUE TITLE
Search function broken on network catalog set as network home page

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-network-catalog#200]
Oregon State has reported a bug with their catalog at https://open.oregonstate.education/, which they've set as their network home page. When searching for any text, or when applying filters while any text is included in the search bar, we're brought to a blank page:

<img width="1437" alt="Screenshot 2023-04-27 at 10 22 15 AM" src="https://user-images.githubusercontent.com/44182629/234940727-0c96587b-7a8e-4b77-b06f-4b2a673ba24a.png">

It appears that after a search the GET parameters in the URL are duplicated, e.g. https://open.oregonstate.education/?per_page=10&sort_by=last_updated&search=climate&per_page=10&sort_by=last_updated#catalog

**Steps to replicate:** 

1. Go to a network's Pages at `https://{domain}/wp/wp-admin/edit.php?post_type=page`
2. Click Edit on the page indicated as the **Front Page**
<img width="237" alt="Screenshot 2023-04-27 at 10 37 52 AM" src="https://user-images.githubusercontent.com/44182629/234944190-d8a6de8d-2afa-4403-861b-a3b419280072.png">

3. In the "Page Attributes" menu set the Template to "Catalog" 
<img width="280" alt="Screenshot 2023-04-27 at 10 35 53 AM" src="https://user-images.githubusercontent.com/44182629/234943592-79f2822e-1630-4547-9368-d6e7ab395412.png">

4. Save changes.
5. Return to the network home page and scroll to the catalog search bar.
6. Type any text into the search bar.
7. Either click the search button or apply a filter from the sidebar. This will return a blank page.

**Comment by SteelWagstaff** [comment]
Os believes the issue is related to this: https://github.com/pressbooks/pressbooks-network-catalog/blob/dev/assets/js/app.js#L72

**Comment by tw77** [comment]
Fix works perfectly on https://dev.pressbooks.network/ when I temporarily set the catalog as the home page. Search function and filters working as expected.
