### ISSUE TITLE
Filtering institutions in the catalog fails when the institution title has an apostrophe

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-network-catalog#203]
When an institution has an apostrophe in its name, it can't be filtered correctly from the network catalog list.  Compare https://staging.pressbooks.network/catalog/?per_page=10&sort_by=last_updated&institutions%5B%5D=Nazarbayev+University&per_page=10&sort_by=last_updated#catalog with https://staging.pressbooks.network/catalog/?per_page=10&sort_by=last_updated&institutions%5B%5D=Nazarbayev+University&per_page=10&sort_by=last_updated#catalog

**Comment by tw77** [comment]
This doesn't seem to be fixed on staging. To recreate:

- I removed "St. Angela's College, Sligo" from "First Staging Book" [Book Info](https://staging.pressbooks.network/firststagingbook/wp-admin/post.php?post=16&action=edit) and saved changes
- I re-added "St. Angela's College, Sligo" in Book Info and saved changes
- I confirm that "St. Angela's College, Sligo" appears in the listed Institutions for this book in https://staging.pressbooks.network/catalog
- I filter https://staging.pressbooks.network/catalog by "St. Angela's College, Sligo"

But I get no results, and the Institution is no longer selected after pressing "Apply Filters":

<img width="1344" alt="Screenshot 2023-06-13 at 12 13 36 PM" src="https://github.com/pressbooks/pressbooks-network-catalog/assets/44182629/ca24deaf-c3d3-445d-abd8-4971593bf66b">

**Comment by tw77** [comment]
That was because the fix wasn't deployed to staging yet, but it is deployed to dev networks.

However, trying this out on a dev network, I'm finding that adding Institutions for a book isn't causing the catalog's left sidebar Institution filters to update. This currently blocks confirming the fix:

<img width="893" alt="Screenshot 2023-06-13 at 2 56 17 PM" src="https://github.com/pressbooks/pressbooks-network-catalog/assets/44182629/591200f7-80df-4c35-92f7-fb2f3c1f5c03">

**Comment by fdalcin** [comment]
> That was because the fix wasn't deployed to staging yet, but it is deployed to dev networks.
> 
> However, trying this out on a dev network, I'm finding that adding Institutions for a book isn't causing the catalog's left sidebar Institution filters to update. This currently blocks confirming the fix:
> 
> <img alt="Screenshot 2023-06-13 at 2 56 17 PM" width="893" src="https://user-images.githubusercontent.com/44182629/245619490-591200f7-80df-4c35-92f7-fb2f3c1f5c03.png">

If I’m not mistaken the list of institutions is cached for 1 hour. This should be solved by flushing the network cache or waiting until the cache expires.

**Comment by tw77** [comment]
Thanks @fdalcin, flushing the cache worked and I see that this fix is working as expected now.
