### ISSUE TITLE
User who clones a book permanently listed as author in network catalog

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-network-catalog#230]
When a user clones a book and the cloned book is added to the network catalog, the user who created the clone is listed as an author for the book in the catalog. This happens even though they don't appear as an author in the book itself (its metadata or its Book Info page).

There doesn't seem to be a way to remove the user from the Author field for the book in the network catalog.

This was found by a QUT network manager (https://pressbooks.zendesk.com/agent/tickets/16222 for internal reference) who has cloned a book originally published on the CAUL platform and is being listed as an author for the cloned book in the QUT network catalog despite not having contributed to the book. She would like to remove her name from the QUT network catalog entry for this book.

I can recreate this issue when cloning a book from Staging to Integrations and also 'in-network' from Integrations to Integrations. After including the book in the Integrations catalog, I see my username permanently listed before the two authors from the source book:
<img width="733" alt="Screenshot 2023-06-13 at 11 05 03 PM" src="https://github.com/pressbooks/pressbooks-network-catalog/assets/44182629/bdd8fc03-a898-4edb-b64b-bf1ca3f61012">

On the book itself, only the original authors are listed in the metadata:

<img width="365" alt="Screenshot 2023-06-13 at 11 04 38 PM" src="https://github.com/pressbooks/pressbooks-network-catalog/assets/44182629/8dc7e418-ab54-4af7-8d5b-775197fea2dd">

**Comment by SteelWagstaff** [comment]
@tw77 and @MichSpieler i believe this issue should have been fixed when we fixed https://github.com/pressbooks/pressbooks/pull/3456. Can one of you confirm that this issue has been resolved and can now be closed at your convenience? This is not urgent.

**Comment by SteelWagstaff** [comment]
I have confirmed that this no longer occur when cloning books from University to Integrations network.
