### ISSUE TITLE
Catalog displays editors even though editor field in book info is empty

### ISSUE THREAD

**Issue by MichSpieler** [pressbooks/pressbooks-network-catalog#236]
A user reported inaccurate book information displayed in their [network's catalog](https://una.pressbooks.pub/catalog/?per_page=10&sort_by=last_updated&search=nursing&per_page=10&sort_by=last_updated#catalog). There are editors listed even though the [book information](https://una.pressbooks.pub/diversity-in-nursing-education/wp-admin/post.php?post=16&action=edit) does not contain any editors. There are no editors displayed on the [book’s home page](https://una.pressbooks.pub/diversity-in-nursing-education/).

I was unable to recreate this issue by cloning the book to a different network. Info from the cloned book displayed correctly in the catalog for the cloned book (no editors displayed).

I tried adding an editor and saving the book information, and then removing the editor and saving again. This had no impact on how the editor information was displayed in the catalog.

**Catalog view**
![image](https://github.com/pressbooks/pressbooks-network-catalog/assets/132941569/2515a3aa-cdc5-44d5-ac48-b1a1dc59dcbc)

**Book homepage**
![image](https://github.com/pressbooks/pressbooks-network-catalog/assets/132941569/44975d9b-da05-4e1b-815b-c3a848de738f)

**Comment by MichSpieler** [comment]
Occurred again with the author field in another book, noted on this ticket (for internal reference): [#16178](https://pressbooks.zendesk.com/agent/tickets/16178)

**Comment by SteelWagstaff** [comment]
Appears to be resolved with latest release of Pressbooks from late August. @MichSpieler please confirm and notify the client(s) who reported these issues, if they haven't already been notified. If I'm mistaken, let me know and I can re-open.
