### ISSUE TITLE
Reported accessibility issues with network catalog

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-network-catalog#246]
Flagged by UTA: SiteImprove noted three accessibility issues with the Pressbooks network catalog. I'll summarize below and for more detail, SiteImprove's report can be viewed at [this link](https://my2.siteimprove.com/Inspector/1043157/A11Y/Page?PageId=73448961275&impmd=9614B7A6B45220FD12A532497FAC2655&conf=a+aa#/).

1. Three element IDs are not unique (this seems to be caused by the use of the same element IDs for mobile and desktop view): `#search`, `#menu-button`, `#search-input-label`
2. The container element with the `role="menu"` doesn't contain certain required-owned elements (according to https://www.w3.org/TR/wai-aria-1.1/#mustContain, it should contain at least one instance of a `menuitem`, `menuitemcheckbox`, or `menuitemradio`)
3. The form field used to indicate the currently shown page in the catalog (e.g. "1 of 3" or "3 of 3") lacks a label.

**Comment by SteelWagstaff** [comment]
For issue 1 we simply need to disambiguate the two sets of IDs (search-mobile, search-desktop, etc.)
For issue 2 we should remove the "role=menu" & the "arialabelled-by" from the filters section
Issue 3 is a false positive -- the id is added dynamically. Users with screen readers will in fact see a proper label.

**Comment by tw77** [comment]
Great, thanks. I've relayed this info to the network manager at UTA who shared the report with us.

**Comment by SteelWagstaff** [comment]
Tested on dev.pressbooks.network/something. Issues 1 & 2 appear to be resolved. No more duplicate IDs and the filters on the left hand side no longer have the misleading ARIA attributes.
