### ISSUE TITLE
Replace flatpickr with more accessible date picker

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-network-catalog#61]
I'd consider alternatives such as those I shared with @SteelWagstaff:

Best:

https://adrianroselli.com/2019/07/maybe-you-dont-need-a-date-picker.html or https://design-system.service.gov.uk/components/date-input/

I had mentioned Pikaday but it appears to have unresolved accessibility issues for screen reader users.

**Comment by SteelWagstaff** [comment]
@greatislander we ended up releasing v1 this week (and closed this issue), but further accessibility review is always welcome.
